/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TireManufacturer
 */
export interface TireManufacturer {
    /**
     * 
     * @type {number}
     * @memberof TireManufacturer
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof TireManufacturer
     */
    name: string;
    /**
     * 
     * @type {Blob}
     * @memberof TireManufacturer
     */
    image: Blob;
    /**
     * 
     * @type {Date}
     * @memberof TireManufacturer
     */
    readonly created?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TireManufacturer
     */
    readonly modified?: Date;
}

/**
 * Check if a given object implements the TireManufacturer interface.
 */
export function instanceOfTireManufacturer(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "image" in value;

    return isInstance;
}

export function TireManufacturerFromJSON(json: any): TireManufacturer {
    return TireManufacturerFromJSONTyped(json, false);
}

export function TireManufacturerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TireManufacturer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
        'image': json['image'],
        'created': !exists(json, 'created') ? undefined : (new Date(json['created'])),
        'modified': !exists(json, 'modified') ? undefined : (new Date(json['modified'])),
    };
}

export function TireManufacturerToJSON(value?: TireManufacturer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'image': value.image,
    };
}

