import Head from "next/head";
import { Inter } from "next/font/google";
import { CaptionCarousel } from "@/components/UI/Carousel/Carousel";
import { Box, Divider, Flex, Heading, useMediaQuery } from "@chakra-ui/react";
import TireListItem from "@/components/Domain/tire/TireListItem";
import React from "react";
import { useGetTireList } from "@/components/Domain/tire/tire.hooks";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { data: tireList, status: tireListStatus } = useGetTireList();
  const [isMobile] = useMediaQuery("(max-width: 480px)");

  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <CaptionCarousel></CaptionCarousel>
      <Divider />
      <Box bgColor={"white"}>
        <Flex h={"2xs"} align={"center"} flexFlow={"column"}>
          <Flex
            mt={12}
            h={"100%"}
            w={"100%"}
            justify={"center"}
            align={"center"}
          >
            <Heading size={"4xl"}>타이어 목록</Heading>
          </Flex>
        </Flex>
        <Flex
          w={"100%"}
          gap={{ sm: 4, base: 8, md: 12 }}
          p={20}
          flexWrap={"wrap"}
          justify={isMobile ? "center" : "space-around"}
          maxW={"1024px"}
          m={"0 auto"}
        >
          {tireListStatus === "success" &&
            tireList.map((tire) => {
              return <TireListItem key={tire.id} tire={tire}></TireListItem>;
            })}
        </Flex>
      </Box>
    </Box>
  );
}
